default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: board_app_development

test:
  <<: *default
  database: board_app_test

production:
  <<: *default
  database: board_app_production
  username: board_app
  password: <%= ENV["BOARD_APP_DATABASE_PASSWORD"] %>
